### PR TITLE
Error view cleanups

### LINKED ISSUE #239: Chill on the snow/emoji/animations when video cannot be played
I finally hit a case where I got an error trying to send a video to min-vid. We probably want to make this a wee bit less animated, or give a bit more contrast since white text on a white/black animated background is a bit hard to read unless you have good vision.

min-vid-snow

Link in question was https://youtu.be/GgC7SDU_6Ec but I can't reproduce now, so may have been some intermittent error. :shrug:

### LINKED ISSUE #258: loading youtube's iframe api fails if not connected to wifi on browser launch
This is two part issue.

1. Provide some error messaging to the user when they are disconnected from the internet and try to watch a video.
2. Attempt to re-fetch the YoutTube iframe api when a network connection has been made so we don't fail in this edge case.

```
min-vid:TypeError: window.YT is undefined
Stack trace:
[9]</module.exports<.componentDidMount@resource://min-vid/data/bundle.js:351:13
invokeComponentDidMountWithTimer@resource://min-vid/data/bundle.js:8864:3
[53]</</<.notifyAll@resource://min-vid/data/bundle.js:3930:9
[132]</ON_DOM_READY_QUEUEING.close@resource://min-vid/data/bundle.js:16213:5
[155]</</Mixin.closeAll@resource://min-vid/data/bundle.js:19301:11
[155]</</Mixin.perform@resource://min-vid/data/bundle.js:19248:11
batchedMountComponentIntoNode@resource://min-vid/data/bundle.js:14503:3
[155]</</Mixin.perform@resource://min-vid/data/bundle.js:19235:13
[106]</ReactDefaultBatchingStrategy.batchedUpdates@resource://min-vid/data/bundle.js:13046:7
batchedUpdates@resource://min-vid/data/bundle.js:16941:3
[121]</</ReactMount._renderNewRootComponent@resource://min-vid/data/bundle.js:14666:5
[121]</</ReactMount._renderSubtreeIntoContainer@resource://min-vid/data/bundle.js:14745:21
[121]</</ReactMount.render@resource://min-vid/data/bundle.js:14766:12
renderApp@resource://min-vid/data/bundle.js:31:3
[1]</window.AppData<.set@resource://min-vid/data/bundle.js:25:5
```

### LINKED ISSUE #273: Error when trying to play Vimeo video
Built locally using `$ ./node_modules/.bin/jpm run -b Nightly`

I've been playing about 10 videos in the same session from https://www.reddit.com/r/videos and started to see some slowdown after the 7-8th video.

Here's the error when I tried to play https://vimeo.com/channels/musicvideos/180016993 from Vimeo.

```
console.error: min-vid:
JPM [error]   Message: TypeError: resp.json is null
  Stack:
    getVimeoUrl/<.onComplete@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/get-vimeo-url.js:9:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
onreadystatechange@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/request.js:104:7
EventHandlerNonNull*runRequest@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/request.js:100:3
Request<.get@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/request.js:145:5
getVimeoUrl@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/get-vimeo-url.js:6:3
launchVideo@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/launch-video.js:25:5
init/onMessageVimeoHandler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/context-menu-handlers.js:51:5
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
workerMessageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js:455:17
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37
```

### LINKED ISSUE #278: Scroll bar is displayed when there is a loading error in the Min-Vid player
[Affected versions]:
- Firefox Dev 50.0a2 (Build ID: 20160919004008)
- Min-Vid v0.1.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Go to https://goo.gl/6aooce .
2. Send the video to Min-Vid player.
3. Play the video.

[Expected result]:
- Video player UI shouldn't break. There are no scroll bars.

[Actual result]:
- The error text is longer than the video container size and a scroll bar is displayed on the right side of the video player. The error text is barely visible,

[Notes]:
- Here is a screen recording with the issue:
error ui

### LINKED ISSUE #283: Link the URL in the error screen to YouTube and open it in a new tab
Currently this is a dead end:

I have to manually copy-pasta the URL and paste it into the address bar to see if the video cannot be played, or cannot be played by Min Vid.
It'd be super neato if we could link the URL and have it open in a new tab.

### LINKED ISSUE #285: Update UX for vevo videos on youtube
Ref: #282

> @6a68 says: _"The [busted Vevo video bug](https://github.com/meandavejustice/min-vid/pull/282#issuecomment-248784959) (see below) is due to Vevo disallowing embeds of their content, so youtube's API won't allow the video to load; it's not specific to this branch.
> Dave's working on an error state to show in cases like that one. Would you mind filing a separate bug and tying it to #280?"_

---

For some reason this video wont play via the Min Vid player via /r/videos, but plays just fine on YouTube: https://youtu.be/Gs069dndIYk?t=9s

The poster image seems to load correctly:

_r_videos

But clicking the Play button either brings up a message about the video not being able to be played back and some message about Vevo, or that displays so quickly, and then jumps into the almost illegible and seizure inducing error message screen saying:

> There was an error loading your video from https://youtube.com/watch?v=Gs069dndIYk

min-vid-vevo

**UPDATE:** Another VEVO example is https://youtube.com/watch?v=M1F0lBnsnkE

---

Not sure how useful it is, but here's a formatted dump of an error from Browser Console and my iTerm window:

```
console.error: min-vid:
  Error: ytCtrl:
Object
    - target = {
  "b":{
    "c":{
      "events":{
      }
    },
    "a":{
      "host":"https://www.youtube.com",
      "title":"video player",
      "videoId":"",
      "width":640,
      "height":360
    },
    "b":true,
    "f":false
  },
  "a":{
  },
  "h":null,
  "closure_uid_583072775":8,
  "g":8,
  "c":1068,
  "B":true,
  "w":[
  ],
  "f":{
    "c":false,
    "s":10,
    "g":[
    ],
    "h":1,
    "a":[
      null,
      "onReady",
      null,
      null,
      "onError",
      null,
      null,
      "onStateChange",
      null,
      null
    ],
    "b":{
      "onReady":[
        1
      ],
      "onError":[
        4
      ],
      "onStateChange":[
        7
      ]
    },
    "v":false
  },
  "s":"player",
  "v":{
    "onReady":true,
    "onError":true,
    "onStateChange":true
  },
  "i":{
  },
  "j":{
    "apiInterface":[
      "cueVideoById",
      "loadVideoById",
      "cueVideoByUrl",
      "loadVideoByUrl",
      "playVideo",
      "pauseVideo",
      "stopVideo",
      "clearVideo",
      "getVideoBytesLoaded",
      "getVideoBytesTotal",
      "getVideoLoadedFraction",
      "getVideoStartBytes",
      "cuePlaylist",
      "loadPlaylist",
      "nextVideo",
      "previousVideo",
      "playVideoAt",
      "setShuffle",
      "setLoop",
      "getPlaylist",
      "getPlaylistIndex",
      "getPlaylistId",
      "loadModule",
      "unloadModule",
      "setOption",
      "getOption",
      "getOptions",
      "mute",
      "unMute",
      "isMuted",
      "setVolume",
      "getVolume",
      "seekTo",
      "getPlayerState",
      "getPlaybackRate",
      "setPlaybackRate",
      "getAvailablePlaybackRates",
      "getPlaybackQuality",
      "setPlaybackQuality",
      "getAvailableQualityLevels",
      "getCurrentTime",
      "getDuration",
      "addEventListener",
      "removeEventListener",
      "getVideoUrl",
      "getDebugText",
      "getVideoEmbedCode",
      "getVideoData",
      "addCueRange",
      "removeCueRange",
      "setSize",
      "getApiInterface",
      "destroy",
      "showVideoInfo",
      "hideVideoInfo"
    ],
    "videoBytesLoaded":0,
    "videoBytesTotal":1,
    "videoLoadedFraction":0,
    "videoStartBytes":0,
    "playlist":null,
    "playlistIndex":-1,
    "playlistId":null,
    "option":null,
    "options":[
    ],
    "muted":false,
    "volume":50,
    "playerState":3,
    "playbackRate":1,
    "availablePlaybackRates":[
      0.25,
      0.5,
      1,
      1.25,
      1.5,
      2
    ],
    "playbackQuality":"unknown",
    "availableQualityLevels":[
    ],
    "currentTime":0,
    "duration":216,
    "videoUrl":"https://www.youtube.com/watch?v=Gs069dndIYk",
    "debugText":"{\"debug_videoId\":\"Gs069dndIYk\",\"gpu\":\"NVIDIA_GeForce_GT_650M_OpenGL_Engine\",\"cgr\":true,\"debug_playbackQuality\":\"unknown\",\"debug_date\":\"Wed Sep 21 2016 17:48:07 GMT-0700 (PDT)\"}",
    "videoEmbedCode":"<iframe width=\"0\" height=\"0\" src=\"https://www.youtube.com/embed/Gs069dndIYk\" frameborder=\"0\" allowfullscreen></iframe>",
    "videoData":{
      "video_id":"Gs069dndIYk",
      "author":"",
      "title":"Earth, Wind & Fire - September"
    },
    "currentTimeLastUpdated_":1474505317.138
  }
}
    - data = 150
```

### LINKED ISSUE #287: Min Vid error when sending missing video to player
Current status:

```sh
$ npm run package
$ ./node_modules/.bin/jpm run -b Nightly
```

When I try and play https://m.youtube.com/watch?v=WdpLMc3kCwc in the mini player, I get the following Terminal output:

```
JPM [info] Starting jpm run on Min Vid
JPM [info] Creating a new profile
console.error: min-vid:
  Unable to apply panel style
console.error: min-vid:
JPM [error]   Message: TypeError: Argument 1 of Window.getComputedStyle is not an object.
  Stack:
    style@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel/utils.js:400:55
onContentReady@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel/utils.js:303:7
EventListener.handleEvent*make@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel/utils.js:334:3
setup@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel.js:171:16
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/disposable.js:48:56
dispatch@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/method/core.js:119:12
Disposable<.initialize@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/disposable.js:71:17
constructor@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/heritage.js:146:23
_create@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/panel-utils.js:174:10
create@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/panel-utils.js:113:14
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/index.js:21:1
evaluate@resource://gre/modules/commonjs/toolkit/loader.js:279:19
load@resource://gre/modules/commonjs/toolkit/loader.js:331:5
main@resource://gre/modules/commonjs/toolkit/loader.js:768:10
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:714:7
handler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/window.js:56:3
EventListener.handleEvent*@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/window.js:54:1
evaluate@resource://gre/modules/commonjs/toolkit/loader.js:279:19
load@resource://gre/modules/commonjs/toolkit/loader.js:331:5
_require@resource://gre/modules/commonjs/toolkit/loader.js:653:16
require@resource://gre/modules/commonjs/toolkit/loader.js:607:12
startup/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:72:21
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:714:7
listener/<@resource://gre/modules/sdk/system/Startup.js:51:46


console.error: min-vid:
  Error: ytCtrl:
Object
    - target = {"b":{"c":{"events":{}},"a":{"host":"https://www.youtube.com","title":"video player","videoId":"","width":640,"height":360},"b":true,"f":true},"a":{},"h":null,"closure_uid_125817075":1,"g":1,"c":5,"B":true,"w":[],"f":{"c":false,"s":10,"g":[],"h":1,"a":[null,"onReady",null,null,"onError",null,null,"onStateChange",null,null],"b":{"onReady":[1],"onError":[4],"onStateChange":[7]},"v":false},"s":"player","v":{"onReady":true,"onError":true,"onStateChange":true},"i":{},"j":{"apiInterface":["cueVideoById","loadVideoById","cueVideoByUrl","loadVideoByUrl","playVideo","pauseVideo","stopVideo","clearVideo","getVideoBytesLoaded","getVideoBytesTotal","getVideoLoadedFraction","getVideoStartBytes","cuePlaylist","loadPlaylist","nextVideo","previousVideo","playVideoAt","setShuffle","setLoop","getPlaylist","getPlaylistIndex","getPlaylistId","loadModule","unloadModule","setOption","getOption","getOptions","mute","unMute","isMuted","setVolume","getVolume","seekTo","getPlayerState","getPlaybackRate","setPlaybackRate","getAvailablePlaybackRates","getPlaybackQuality","setPlaybackQuality","getAvailableQualityLevels","getCurrentTime","getDuration","addEventListener","removeEventListener","getVideoUrl","getDebugText","getVideoEmbedCode","getVideoData","addCueRange","removeCueRange","setSize","getApiInterface","destroy","showVideoInfo","hideVideoInfo"],"videoBytesLoaded":0,"videoBytesTotal":1,"videoLoadedFraction":0,"videoStartBytes":0,"playlist":null,"playlistIndex":-1,"playlistId":null,"option":null,"options":[],"muted":false,"volume":50,"playerState":3,"playbackRate":1,"availablePlaybackRates":[0.25,0.5,1,1.25,1.5,2],"playbackQuality":"unknown","availableQualityLevels":[],"currentTime":0,"duration":0,"videoUrl":"https://www.youtube.com/watch?v=WdpLMc3kCwc","debugText":"{\"debug_videoId\":\"WdpLMc3kCwc\",\"gpu\":\"NVIDIA_GeForce_GT_650M_OpenGL_Engine\",\"cgr\":true,\"debug_playbackQuality\":\"unknown\",\"debug_date\":\"Wed Sep 21 2016 17:30:03 GMT-0700 (PDT)\"}","videoEmbedCode":"<iframe width=\"0\" height=\"0\" src=\"https://www.youtube.com/embed/WdpLMc3kCwc\" frameborder=\"0\" allowfullscreen></iframe>","videoData":{"video_id":"WdpLMc3kCwc","author":"","title":""},"currentTimeLastUpdated_":1474504208.902}}
    - data = 150
```

May be specific to that video, but it was one of the first videos on /r/videos. 

_r_videos

Ah, looks like the video may have been taken down:

> This video has been removed for violating YouTube's policy on harassment and bullying.

### PR DESCRIPTION
**Pull request by meandavejustice**
- clean up Error View styles fixes #239
- handle vimeo request errors fixes #273
- get rid of scroll bar in error view fixes #278
- handle case where yt embed api lib is not loaded when
not connected to internet (this pr bundles it into the build)
fixes #258
- Handle errors from VEVO playback fixes #285
- Handle errors from missing videos fixes #287
- link to page url in error view fixes #283
- cleanup require calls to remove '.js' extension

### CODE REVIEW

File: data/www-widgetapi.js [hunk 1]
```diff
@@ -0,0 +1,159 @@
+(function(){var g,k=this;function l(a){a=a.split(".");for(var b=k,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b}
```
Comment (pdehaan) [inline data/www-widgetapi.js]: What is this?
Not sure if this is 3rd party or whatever.

File: lib/get-vimeo-url.js [hunk 2]
```diff
@@ -6,7 +6,13 @@ function getVimeoUrl(videoId, cb) {
   Request({
     url: 'https://player.vimeo.com/video/' + videoId + '/config',
     onComplete: function (resp) {
-      cb(null, resp.json.request.files.progressive[0].url);
+      if (!resp.json) cb('Could not connect to vimeo.com');
```
Comment (pdehaan) [inline lib/get-vimeo-url.js]: I'm a bit confused here.
Something feels 🐟 since we aren't doing a `return` here, so we could technically call the callback twice (here and on line 14 below).
Or more likely we'd implode on L14 below since `resp.json` would be falsey here.

File: data/panel.css [hunk 3]
```diff
@@ -59,15 +59,29 @@ video#video {
     background-repeat: no-repeat;
     background-size: cover;
     background: url('img/static.gif');
+    height: 100%;
+}
+
+.error-message-container {
+    background: #00000080;
```
Comment (pdehaan) [inline data/panel.css]: I'm not a CSS Wizard, but not sure on the `#RRGGBBAA` support yet.
After a bit of searching, MDN comes back with https://developer.mozilla.org/en-US/docs/Web/CSS/color_value which lists FF49+ for `#RRGGBBAA` versus FF3+ for `rgba()` syntax.

/cc My CSS Spirit Guide, Mr. @johngruen

File: data/www-widgetapi.js (hunk 1 above)
Comment (meandavejustice) [inline data/www-widgetapi.js]: This is youtube's iframe api lib. I decided to check it in order to simplify and fix #258 . We also have once less http request and we are a bit more secure.

File: lib/get-vimeo-url.js (hunk 2 above)
Comment (meandavejustice) [inline lib/get-vimeo-url.js]: DOH! thanks for catching that. I'll fix that up

File: data/panel.css (hunk 3 above)
Comment (meandavejustice) [inline data/panel.css]: I meant to check on this. I basically just copied it out of the css editor. I'll update to something with more support just to be safe

File: data/www-widgetapi.js (hunk 1 above)
Comment (pdehaan) [inline data/www-widgetapi.js]: We may want to add their copyright header or URL+version in the comment header or something
Otherwise in a week or three it's just a random minimized JS file in our repo that we don't know where it came from.

Comment (meandavejustice) [inline data/www-widgetapi.js]: Good call

Comment (pdehaan) [inline data/www-widgetapi.js]: I mean, bonus points if we can install this via npm/GitHub or some other managed way so we don't need to host a copy at all, but we can do that in the future.

File: data/default.html [hunk 4]
```diff
@@ -20,7 +20,55 @@
   </head>
   <body>
     <div id="container"></div>
-    <script src="https://www.youtube.com/iframe_api"></script>
+    <script>
+     // from youtube.com/iframe_api
```
Comment (6a68) [inline data/default.html]: @meandavejustice Is there some reason you're inlining this, rather than create a vendor bundle? Just to save time, maybe?

**Comment by 6a68** [comment]
@meandavejustice When I load the bad youtube link, I see the player view with the 'end of video' view, not the error view:



If I click the big 'reload' icon, I do get the error screen, and I see two errors in the console (see below). If I try to load the bad link again, I again see the end of video player view.

> console.error: min-vid: 
  Error: ytCtrl: 
Object
    - target = {"b":{"c":{"events":{}},"a":{"host":"http://www.youtube.com","title":"video player","videoId":"","width":640,"height":360},"b":true,"f":true},"a":{},"h":null,"closure_uid_785193337":1,"g":1,"c":5,"B":true,"w":[],"f":{"c":false,"s":10,"g":[],"h":1,"a":[null,"onReady",null,null,"onError",null,null,"onStateChange",null,null],"b":{"onReady":[1],"onError":[4],"onStateChange":[7]},"v":false},"s":"player","v":{"onReady":true,"onError":true,"onStateChange":true},"i":{},"j":{"apiInterface":["cueVideoById","loadVideoById","cueVideoByUrl","loadVideoByUrl","playVideo","pauseVideo","stopVideo","clearVideo","getVideoBytesLoaded","getVideoBytesTotal","getVideoLoadedFraction","getVideoStartBytes","cuePlaylist","loadPlaylist","nextVideo","previousVideo","playVideoAt","setShuffle","setLoop","getPlaylist","getPlaylistIndex","getPlaylistId","loadModule","unloadModule","setOption","getOption","getOptions","mute","unMute","isMuted","setVolume","getVolume","seekTo","getPlayerState","getPlaybackRate","setPlaybackRate","getAvailablePlaybackRates","getPlaybackQuality","setPlaybackQuality","getAvailableQualityLevels","getCurrentTime","getDuration","addEventListener","removeEventListener","getVideoUrl","getDebugText","getVideoEmbedCode","getVideoData","addCueRange","removeCueRange","setSize","getApiInterface","destroy","showVideoInfo","hideVideoInfo"],"videoBytesLoaded":0,"videoBytesTotal":1,"videoLoadedFraction":0,"videoStartBytes":0,"playlist":null,"playlistIndex":-1,"playlistId":null,"option":null,"options":[],"muted":false,"volume":50,"playerState":5,"playbackRate":1,"availablePlaybackRates":[0.25,0.5,1,1.25,1.5,2],"playbackQuality":"unknown","availableQualityLevels":[],"currentTime":0,"duration":0,"videoUrl":"https://www.youtube.com/watch","debugText":"{\"debug_videoId\":null,\"gpu\":\"NVIDIA_GeForce_GT_750M_OpenGL_Engine\",\"cgr\":true,\"debug_playbackQuality\":\"unknown\",\"debug_date\":\"Thu Sep 22 2016 15:49:10 GMT-0700 (PDT)\"}","videoEmbedCode":"<iframe width=\"0\" height=\"0\" src=\"https://www.youtube.com/embed/undefined\" frameborder=\"0\" allowfullscreen></iframe>","videoData":{"video_id":null,"author":"","title":""},"currentTimeLastUpdated_":1474584550.792}}
    - data = 2
console.error: min-vid: 
  Error: ytCtrl: 
Object
    - target = {"b":{"c":{"events":{}},"a":{"host":"http://www.youtube.com","title":"video player","videoId":"","width":640,"height":360},"b":true,"f":true},"a":{},"h":null,"closure_uid_785193337":1,"g":1,"c":5,"B":true,"w":[],"f":{"c":false,"s":10,"g":[],"h":1,"a":[null,"onReady",null,null,"onError",null,null,"onStateChange",null,null],"b":{"onReady":[1],"onError":[4],"onStateChange":[7]},"v":false},"s":"player","v":{"onReady":true,"onError":true,"onStateChange":true},"i":{},"j":{"apiInterface":["cueVideoById","loadVideoById","cueVideoByUrl","loadVideoByUrl","playVideo","pauseVideo","stopVideo","clearVideo","getVideoBytesLoaded","getVideoBytesTotal","getVideoLoadedFraction","getVideoStartBytes","cuePlaylist","loadPlaylist","nextVideo","previousVideo","playVideoAt","setShuffle","setLoop","getPlaylist","getPlaylistIndex","getPlaylistId","loadModule","unloadModule","setOption","getOption","getOptions","mute","unMute","isMuted","setVolume","getVolume","seekTo","getPlayerState","getPlaybackRate","setPlaybackRate","getAvailablePlaybackRates","getPlaybackQuality","setPlaybackQuality","getAvailableQualityLevels","getCurrentTime","getDuration","addEventListener","removeEventListener","getVideoUrl","getDebugText","getVideoEmbedCode","getVideoData","addCueRange","removeCueRange","setSize","getApiInterface","destroy","showVideoInfo","hideVideoInfo"],"videoBytesLoaded":0,"videoBytesTotal":1,"videoLoadedFraction":0,"videoStartBytes":0,"playlist":null,"playlistIndex":-1,"playlistId":null,"option":null,"options":[],"muted":false,"volume":50,"playerState":-1,"playbackRate":1,"availablePlaybackRates":[0.25,0.5,1,1.25,1.5,2],"playbackQuality":"unknown","availableQualityLevels":[],"currentTime":0,"duration":0,"videoUrl":"https://www.youtube.com/watch","debugText":"{\"debug_videoId\":null,\"gpu\":\"NVIDIA_GeForce_GT_750M_OpenGL_Engine\",\"cgr\":true,\"debug_playbackQuality\":\"unknown\",\"debug_date\":\"Thu Sep 22 2016 15:49:10 GMT-0700 (PDT)\"}","videoEmbedCode":"<iframe width=\"0\" height=\"0\" src=\"https://www.youtube.com/embed/undefined\" frameborder=\"0\" allowfullscreen></iframe>","videoData":{"video_id":null,"author":"","title":""},"currentTimeLastUpdated_":1474584554.377}}
    - data = 2

**Comment by 6a68** [comment]
Could I be doing something wrong?

If I load the bad vine URL, I see the loading screen forever, with this error in the console:
>   LaunchVideo failed to get the streamUrl: 
  https://vine.co/v/5BKrxxxixt1j not reachable at this time

Similarly, if I load the bad vimeo URL, I see the loading screen forever, with a similar error:
>  LaunchVideo failed to get the streamUrl: 
  This video does not exist.

**Comment by 6a68** [comment]
These are the steps I took to build the code and launch a fresh dev edition profile:

- check out the branch
- `npm install`
- `npm build-script`
- `jpm run -b /Applications/FirefoxDeveloperEdition.app`

**Comment by 6a68** [comment]
I'm having the same problems on my windows 10 machine as on my macbook:

- all the good links work fine
- bad youtube link goes straight to end of video screen
- bad vimeo, vine links never leave the loading screen

**Comment by meandavejustice** [comment]
Looks like vimeo got goofed up in the rebase.
