### PR TITLE
Overlay icon

### LINKED ISSUE #64: min-vid initialization from embedded video logo

### LINKED ISSUE #84: Audio streams getting orphaned when opening minified videos in a new tab
Found locally in **min-vid@0.1.0** (which isn't helpful since I think all add-ons are that version). 

```sh
$ git rev-parse HEAD # bc4abd73a0f2cf089c147b9cfa0dbbe0d8824430
```

---

### Steps to reproduce:
1. Build and install add-on locally.
1. Navigate to https://www.reddit.com/r/videos and find a video from "(youtube.com)".
1. Right-click the link and select "Send to mini-player" from context menu.
1. Hover over the video and press the "Play" button (not sure if these should auto-play by default since we can only have one pop-up at a time).
1. With the video playing (and some rockin' audio happening), click the "Open in new tab" button.
1. The video should play in a new tab, but you'll still hear audio from the mini player, which is no longer visible. So if the new YouTube.com window starts playing audio, you'll have TWO audio streams which are out of sync, with no way to close the original audio stream short of quitting your browser.

### Expected results:
When opening a video in a new tab, we should make sure we stop the video playback in the mini-player before destroying that popup.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #64 
- add overlay-icon.js for adding icon to dom and handling actions
- add overlay-icon.css for styling icon
- supports youtube(watch/home) and vimeo(detail/home) as well as vimeo and youtube embeds
- fix orphaned audio streams on `send-to-tab` and `close` fixes #84 

I've tried to find a good percentage ratio for the `width`, `top`, and `left` css attributes for the icon container. Something that will look reasonable for the many different sizes. I'm happy to take suggestions for tweaks to this, but I'd like to not hold up this pr for css polish that can be covered in #72 

### Links for testing:
- [youtube home](https://www.youtube.com)
- [youtube watch](https://www.youtube.com/watch?v=Wjku6BZz3EQ)
- [vimeo home](https://vimeo.com/home)
- [vimeo detail](https://vimeo.com/15540231)
- [vimeo embed](http://www.ubu.com/film/anger_puce.html)

### Testing plan:
1. Install addon
2. test both "youtube watch" and "vimeo detail" links above with the context menu
3. navigate to all links above and make sure videos can be sent to min-vid via overlay icon.

### Known issues:
- launching min-vid from `vimeo detail` or `vimeo embed` also starts the video. It seems `stopImmediatePropagation` and `addEventListener capture argument` aren't working. Will probably file a separate issue to be fixed later.
- There seems to be an issue getting the icons attached when navigating around youtube.com, this seems to be because it is a single page app, and [page-mod](https://duckduckgo.com/l/?kh=-1&uddg=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FMozilla%2FAdd-ons%2FSDK%2FHigh-Level_APIs%2Fpage-mod) only runs on new pages. This will probably be a simple fix by just running the attach methods every once in a while. I'm holding out for a bit to see if we can think of a more elegant way than an interval.

### CODE REVIEW

**Comment by 6a68** [comment]
gah, so many reviews! looking right now

**Comment by pdehaan** [comment]
Needs rebase.
Seeing slight issue with the hover background:

1. No hover:
youtube

2. Hover over video:
youtube

3. Hover over icon:
youtube

**Comment by pdehaan** [comment]
Same leak w/ full sized videos on YouTube.com:

justice_league_official_trailer__2017__ben_affleck_dc_superhero_movie_hd_-_youtube

**Comment by pdehaan** [comment]
I only see the overlay on https://vimeo.com/48396889 when I hover over the 100x100 pixels in the top left.

---

No overlays on Vimeo Recommended thumbnails:
nike_bmx_in_taipei_on_vimeo

---

Clicking the overlay in this minified floating video opens min-vid, but toggles video in upper-left. Basically dueling minified PiP players:
nike_bmx_in_taipei_on_vimeo

**Comment by pdehaan** [comment]
No overlays on Vimeo search results (but I do get a "Send to mini player" context menu item):

danny_macaskill_in_videos_on_vimeo

**Comment by 6a68** [comment]
minimized view looks kinda funny, and there's no way to re-maximize it, but let's fix in a followup PR:

File: data/icon-overlay.js [hunk 1]
```diff
@@ -0,0 +1,90 @@
+const host = window.location.host;
+
+// YOUTUBE HOME PAGE
+// TODO: listen for infinite scrollesque updates and apply this again
+// if necessary
```
Comment (6a68) [inline data/icon-overlay.js]: File a bug and add the bug number to the TODO

File: data/icon-overlay.js [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+const ytHomeContainers = Array.from(document.querySelectorAll('#feed .yt-lockup-thumbnail'));
+if ((host.indexOf('youtube.com') > -1) && ytHomeContainers.length) {
+  ytHomeContainers.forEach(el => {
+    el.classList.add('minvid__overlay__wrapper');
+    const tmp = getTemplate();
+    tmp.addEventListener('click', function(ev) {
+      evNoop(ev);
+      const partialUrl = el.querySelector('.yt-uix-sessionlink').getAttribute('href');
```
Comment (6a68) [inline data/icon-overlay.js]: `querySelector` returns `null` if nothing's found, so the `.getAttribute` could throw...unless `el` is some special thing

File: data/icon-overlay.js [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+      if (partialUrl.length) {
```
Comment (6a68) [inline data/icon-overlay.js]: Seems weird to check the length of a string. Maybe just `if (partialUrl)`, since it does the same thing?

File: data/icon-overlay.js [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+        self.port.emit('launch', {
+          url: 'https://youtube.com' + partialUrl,
+          domain: host
+        });
+      } else console.error('Error parsing url from YT home page', partialUrl); // eslint-disable-line no-console
```
Comment (6a68) [inline data/icon-overlay.js]: wrap the else clause in curly braces, I've been burned by this ("I'll just add another line to the else clause...")

File: data/icon-overlay.js [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+  const iconEl = document.createElement('div');
+
+  containerEl.className = 'minvid__overlay__container';
+  iconEl.className = 'minvid__overlay__icon';
+
+  containerEl.appendChild(iconEl);
+  return containerEl;
+}
+
+function evNoop(ev) {
```
Comment (6a68) [inline data/icon-overlay.js]: `handleEvent` might be a more readable API name

Comment (6a68) [inline data/icon-overlay.js]: oh wait, I think `handleEvent` actually has special meaning...never mind

File: data/icon-overlay.js [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+    const tmp = getTemplate();
+    tmp.addEventListener('click', function(ev) {
+      evNoop(ev);
+      const fauxEl = el.querySelector('.faux_player');
+      if (fauxEl) {
+        self.port.emit('launch', {
+          url: 'https://vimeo.com/' + fauxEl.getAttribute('data-clip-id'),
+          domain: host
+        });
+      } else console.error('Error: failed to locate vimeo url'); // eslint-disable-line no-console
```
Comment (6a68) [inline data/icon-overlay.js]: else curly braces here too

File: index.js [hunk 7]
```diff
@@ -87,54 +86,64 @@ cm.Item({
...
+  });
+}
 
+function launchVimeo(url) {
+  const id = getVideoId(url);
+  updatePanel({domain: 'vimeo.com', id: id, src: ''});
+  getVimeoUrl(id, function(err, streamUrl) {
+    if (!err) updatePanel({src: streamUrl});
+  });
+}
```
Comment (6a68) [inline index.js]: As we add more video providers, it might be nice to just have one function and pass in the stuff that varies as a data object:
`{ url: url, getUrlFn: getVimeoUrl, domain: 'vimeo.com' }`
or
`{ url: url, getUrlFn: getVideoId, domain: 'youtube.com' }`

**Comment by 6a68** [comment]
> launching min-vid from vimeo detail or vimeo embed also starts the video. It seems stopImmediatePropagation and addEventListener capture argument aren't working. Will probably file a separate issue to be fixed later.

@meandavejustice Have you tried using a capturing listener, instead of a bubbling listener? Might help, not sure though.

**Comment by 6a68** [comment]
@meandavejustice OK, I've done a pass, the code's good overall. Only real concern is not null-checking the `querySelector` call, other than that these are minor stylistic nits. Rebase, fix little things, and merge away :beers:

File: data/icon-overlay.js (hunk 4 above)
Comment (pdehaan) [inline data/icon-overlay.js]: **PROTIP:** ESLint has a [`curly`](http://eslint.org/docs/rules/curly) for this very thing:

```sh
$ eslint .

/Users/pdehaan/dev/github/mozilla/min-vid/app.js
  135:5  error  Expected { after 'if' condition  curly

/Users/pdehaan/dev/github/mozilla/min-vid/data/resize-listener.js
   7:7  error  Expected { after 'if' condition  curly
  12:5  error  Expected { after 'if' condition  curly

/Users/pdehaan/dev/github/mozilla/min-vid/index.js
   30:5  error  Expected { after 'if' condition  curly
   31:5  error  Expected { after 'else'          curly
   79:7  error  Expected { after 'if' condition  curly
   97:7  error  Expected { after 'if' condition  curly
  113:7  error  Expected { after 'if' condition  curly

✖ 8 problems (8 errors, 0 warnings)
```

---

PR incoming!

**Comment by meandavejustice** [comment]
* fixed querySelector check cc/ @6a68 
* created `launchVideo` function cc/ @6a68 
* `contextMenuLabel` is now defined in one place
* fixed icon background transparency leak
* created #112 for tracking overlay-icon edge cases cc/ @pdehaan 
* created #111 for adding context menu to vimeo detail page
