### PR TITLE
Fixes #27 Doesn't work on youtube.com/watch pages

### LINKED ISSUE #27: Doesn't work on youtube.com/watch pages
Youtube shows a custom context menu if you right-click over the youtube.com/watch player (see screenshot below).

Maybe we could have a toolbar button light up if the window.location is youtube.com/watch?..., since it'd be easy to grab the window.location and send that to the picture-in-picture player.

screen shot 2016-05-20 at 12 04 56 pm

### PR DESCRIPTION
**Pull request by kaganjd**
Within cm.SelectorContext, this uses "class*=" instead of "href*=" to trigger the context menu on YouTube.com main pages and channel pages.

For some reason, using "href*=/watch?v" wasn't working.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ var cm = require("sdk/context-menu");
 
 cm.Item({
   label: "Send to mini player",
-  context: cm.SelectorContext('[href*="youtube.com"], [href*="youtu.be"]'),
+  context: cm.SelectorContext('[class*="yt-uix-sessionlink"], [href*="youtube.com"], [href*="youtu.be"]'),
```
Comment (meandavejustice) [inline index.js]: I think that checks for classname and attributes specific to the youtube domain should be in a separate call to `cm.Item`

This would probably look something like:

``` js
cm.Item({
  label: "Send to mini player",
  context: [
    cm.URLContext(['*.youtube.com']),
    cm.SelectorContext('href*="watch"')
  ],
```

Comment (kaganjd) [inline index.js]: That makes sense. Thanks! 

New commit below. Should I squash them all into one?

Comment (meandavejustice) [inline index.js]: squashing would be great, thank you!
