### PR TITLE
Remove usage of const in for loop for ff49

### LINKED ISSUE #466: Min-Vid 0.3.2 from Test Pilot is not working on latest Firefox release 49.0.2
**[Affected versions]:**
-Firefox User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
-Firefox Build ID: 20161019084923
-Min-Vid v0.3.2-release

**[Affected Platforms]:**
-Ubuntu 14.04 x64
-Windows 8.1 x64
-Mac OS X 10.11.6

**[Prerequisites]:**
-Latest release Min-Vid add-on version (0.3.2 - Test Pilot) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube).
3. Send a video to Min-Vid player.

**[Expected result]:**
-Video is sent to Min-Vid player.

**[Actual result]:**
-`console.error: min-vid: Message: SyntaxError: missing = in const declaration...core.js:106` error is displayed in browser console.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #466
- fix issue with uglify-js https://github.com/mishoo/UglifyJS2/issues/1340
- bump version to 0.3.3
- add data/controls.js to .eslintignore because of `deep-assign` code paste

### CODE REVIEW

File: data/controls.js [hunk 1]
```diff
@@ -29,22 +29,78 @@ window.addEventListener('addon-message', function(ev) {
 /*
  * since this file is not bundled, we cannot use the deep-assign
  * package that we are using in the client code.
+ * from sindresorhus/deep-assign
  */
 
-function isObject(item) {
-  return (item && typeof item === 'object' && !Array.isArray(item));
+'use strict';
```
Comment (pdehaan) [inline data/controls.js]: Not sure if this works. I thought that `"use strict"` needed to appear before any other statements in a file/function. (per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)

IIRC, the "use strict" statement will just be ignored though, so I guess no real harm.

**Comment by fritx** [comment]
Nice it works again against https://github.com/mishoo/UglifyJS2/issues/1340
