### PR TITLE
Close min vid when last firefox window is closed

### LINKED ISSUE #539: Min-Vid is not closed when closing Firefox
[Notes]:
- If you try to reopen the browser while the Min-Vid player is still open you will get the "Firefox is already opened..." message.
- If you close the Min-Vid player after closing the browser, the player loses it's custom position on the screen.

[Affected versions]:
- Nightly 53.0a1
- Min-Vid 0.3.3b (built on 12/27/2016)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.3b) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.youtube.com and send a video to the mini player.
3. Observe the Min-Vid while closing the browser.

[Expected result]:
- The Min-Vid player is also closed.

[Actual result]:
- The Min-Vid player remains open.

[Additional Notes]:
- The issue is also reproducible on the Test Pilot version of the add-on.
- Attached a screen recording of the issue:
min-vid is not closed when closing firefox

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #539

### CODE REVIEW

**Comment by 6a68** [comment]
This works on Mac / Nightly and Windows 10 / Nightly for closing windows/tabs with the mouse or keyboard, and for closing all windows from the start menu. I can also close Firefox with hotkeys when the min-vid window is focused. Pretty sure we're good here. Merging.

File: lib/window-utils.js [hunk 1]
```diff
@@ -147,6 +155,7 @@ function destroy(isUnload) {
   closeWindow();
   if (isUnload) {
     Services.obs.removeObserver(onWindowClosed, 'xul-window-destroyed', false);
+    Services.obs.removeObserver(closeRequested, 'quit-application-granted', false);
```
Comment (6a68) [inline lib/window-utils.js]: @meandavejustice I missed this, but you're removing the wrong message when exiting. I'll open a PR quickly to fix.
