### PR TITLE
Draggable sdk panel cleanups

### LINKED ISSUE #136: Don't hide-then-show the panel when dragging
We can do `getActiveView(panel)` to get a XUL Panel, and then we can toggle attributes on the panel itself to expand it. This should help with the initial flicker when the drag starts.

### LINKED ISSUE #140: Randomly, Min-Vid player continues to move although the mouse button has been released
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.1) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a video from youtube.com.
2. Click on the overlay icon or right-click on a video from the side-bar and choose from the context menu "Send to mini player".
3. Click and drag the Min-Vid player to a different place.
4. Release the mouse button and keep moving the mouse.

[Expected result]:
- When mouse button is up, the Min-Vid player stops moving.

[Actual result]:
- Min-Vid player continues to move although the mouse button has been released.

[Notes]:
- You might need to repeat steps 3 and 4 a few times in order to reproduce the issue.
- Added a screen recording with the issue: https://goo.gl/us9mrv

### LINKED ISSUE #144: Panel dimensions are incorrect while dragging
See screencast from #140: when the drag starts, it's possible to drag the player off the right edge of the parent browser window, and to drag the player behind an invisible border 100-200 pixels in from the left edge of the parent browser window.

### LINKED ISSUE #145: Dragging should be constrained by the iframe's boundaries
(Split off from #140)

We should prevent the player view from following the mouse pointer outside the iframe's container element. This should fix the issue where dropping after a drag isn't registered on the iframe.

### LINKED ISSUE #149: Min-vid player jumps on the top left part of the page when pressing any of the controls buttons
[Affected versions]:
- Nightly 51.0a1
- Min-vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-vid add-on version (v0.1.1) was installed on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to YouTube.com page.
2. Click on the overlay icon or right-click on a video from the side-bar and choose from the context menu "Send to mini player". 
3. Click on any of the player buttons.

[Expected result]:
- The video starts playing without changing player position.

[Actual result]:
- The video starts playing but the player jumps on the top left part of the page.

[Notes]:
- No matter where the player is positioned, clicking the player controls will move the player in top left side of the page.
- If the player is moved anywhere on the page and clicked anywhere on his surface (except player controls), it goes down a few more pixels at each click until the bottom part is reached.
- Added a screen recording with the issue: http://goo.gl/IDQFLv.

### LINKED ISSUE #154: Dragging player volume button wrongly moves the entire player
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.1) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a video from youtube.com.
2. Click on the overlay icon or right-click on a video from the side-bar and choose from the context menu "Send to mini player".
3. Clik the "Play" button in the Min-Vid player in order to start the video playback.
4. Click and drag the volume button of the player.

[Expected result]:
- The volume button is being moved in the draggged direction.

[Actual result]:
- The entire player is being moved in the draggged direction.

[Notes]:
- Added a screen recording with the issue: http://goo.gl/YIhwkS

### LINKED ISSUE #155: Scrollbars in min vid popup
I seem to be able to get some scrollbars when sending a video to a pop up.

Video in question was first YouTubes video on reddit.com/r/videos: 
https://www.youtube.com/watch?v=_5jnn1AIt7Q

Then just scroll around in your trackpad in the popup.

add-ons_manager_and_fresh_min_vid_build_-_pdehaan_mozilla_com_-_mozilla_mail

### LINKED ISSUE #167: Sometimes dragging min-vid player causes it to shift within the frame
Continuing my trend of garbage bugs with not enough context or repro steps...

I've hit this 2-3 times this afternoon where I go to do something and interact w/ Min Vid player and end up accidentally dragging the window, but it doesnt move the video, but instead it shifts the video within the iframe/window that it's in, meaning the video just gets clipped and cropped in unexpected ways.

_r_videos_and_browser_console_and_csv_parser___node_js_csv_project_and_blok_web-ext-artifacts_at_master_ _mozilla_blok

### LINKED ISSUE #197: I can drag the video inside the draggable xul box thing
Not quite sure how to describe this bug but it's pretty bad. Maybe @meandavejustice old dragging code is still present w/in the new draggable?

https://www.dropbox.com/s/ku37nhe4s8qfd1g/Screen%20Shot%202016-09-06%20at%206.01.56%20PM.png?dl=0

### PR DESCRIPTION
**Pull request by meandavejustice**
- remove `react-draggable` dep
- move `draggifyPanel` method to `lib/make-panel-draggable.js`
- remove `lib/get-document-dimensions.js`
- remove handling of `expand-panel` and `shrink-panel`
- remove draggable code from `components/app-view.js`
- fixes #136 
- fixes #167
- fixes #155
- fixes #154
- fixes #145
- fixes #149
- fixes #144
- fixes #140
- fixes #197

### CODE REVIEW

**Comment by 6a68** [comment]
This looks exciting. I'll review it in a bit

File: index.js [hunk 1]
```diff
@@ -26,48 +24,11 @@ const panel = require('sdk/panel').Panel({
...
-  dragHandle.onmouseup = () => { dragHandle.style.cursor = 'grab' }
-  panelEl.appendChild(dragHandle);
-
-  // make the drag handle only visible on mouseover
-  panelEl.onmouseenter = () => { dragHandle.setAttribute('hidden', false) };
-  panelEl.onmouseleave = () => { dragHandle.setAttribute('hidden', true) };
-
-  parentEl.appendChild(panelEl);
+// check for linux here
+if (system.platform !== 'linux') {
```
Comment (6a68) [inline index.js]: It might be better to enable dragging only if `system.platform` is `winnt` or `darwin`. There is a [huge list](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/OS_TARGET) of known supported platforms; as the linked page says, this value is just the output of `uname -s`, so there are still others out there.

File: lib/make-panel-draggable.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+  // Next, we need a XUL document to create a drag handle. There may be better
+  // ways to obtain the document element, but this works:
+  let doc = parentEl;
+  while (doc !== null && doc.nodeType !== 9) {
+    doc = doc.parentNode;
+  }
+
+  const dragHandle = doc.createElement('label');
+  dragHandle.id = 'backdragspot';
+  // TODO: the drag handle doesn't seem to be visible--maybe the iframe is set
```
Comment (6a68) [inline lib/make-panel-draggable.js]: This TODO is stale & can be removed

File: index.js (hunk 1 above)
Comment (meandavejustice) [inline index.js]: Good point. I've opened #192 as a followup to handle this all correctly.

**Comment by 6a68** [comment]
@meandavejustice LGTM and works :+1: Happy to merge once the system.platform thing is changed

**Comment by 6a68** [comment]
I'll add the system.platform thing to 192
