### PR TITLE
Parse cc option from youtube watch page and pass to min vid

### LINKED ISSUE #522: Closed Captions/Subtitles are displayed in min-Vid player even if they are set to OFF on YouTube
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid 0.3.3b

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Min-Vid add-on version (0.3.3b) was previously installed on a clean profile.
-Need to have an YouTube video that has Closed Captions/Subtitles, not auto-translate. ( eg. https://www.youtube.com/watch?v=P3Ew8dCUonE )

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube.
3. Search for a video that has subtitles (eg. https://www.youtube.com/watch?v=P3Ew8dCUonE ).
4. Play the video on YouTube and set the Closed Captions/Subtitles to OFF.
5. Open the video in Min-Vid player.

**[Expected result]:**
- Closed Captions/Subtitles are OFF in Min-Vid player.

**[Actual result]:**
-  Closed Captions/Subtitles are displayed in Min-Vid player.

**[Notes]:**
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiaUlzWGx1Q2xEcHc) is a recording of the issue.
-Closed Captions/Subtitles should be displayed in Min-Vid player only if they are set to ON for the played video on YouTube.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #522 
- refs #68

### CODE REVIEW

File: lib/get-youtube-url.js [hunk 1]
```diff
@@ -3,14 +3,17 @@ const qs = require('sdk/querystring');
...
+  if (!cc) cc = false;
+
   const params = qs.stringify({
     autoplay: time ? 1 : 0,
     modestbranding: 1,
     controls: 0,
     disablekb: 0,
     enablejsapi: 1,
     fs: 0,
+    cc_load_policy: +cc, // force boolean to number
```
Comment (6a68) [inline lib/get-youtube-url.js]: Seems weird to use `Boolean(foo)` instead of `!!foo`, but then use `+foo` instead of `Number(foo)`.

I personally prefer the shorthand version, but I care more that it's consistent. Your call on what approach to pick.

Comment (meandavejustice) [inline lib/get-youtube-url.js]: I agree, I'll update this to the shorthand

Comment (6a68) [inline lib/get-youtube-url.js]: Cool. Feel free to merge this yourself when that's done :+1:
