### PR TITLE
Vimeo logged-out homepage overlay icon/context menu

### LINKED ISSUE #209: Min-Vid overlay and context menu option don't appear for videos on Vimeo homepage
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to Vimeo.
3. Hover a video thumbnail.

[Expected result]:
- The Min-Vid overlay appears on the video.

[Actual result]:
- The Min-Vid overlay does not appear for videos.

[Additional Notes]:
- "Send to mini player" context menu option is missing from videos displayed on main page.
- The Min-Vid overlay also doesn't appear for related videos, but the context menu option does appear.
- Attached a screen recording of the issue http://goo.gl/bjsT6Y.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #209

### CODE REVIEW

File: lib/context-menu-handlers.js [hunk 1]
```diff
@@ -126,6 +126,23 @@ function init(panel) {
     label: contextMenuLabel,
     context: [
       cm.URLContext(['*.vimeo.com']),
+      cm.SelectorContext('.iris_video-vital__overlay.iris_link-box')
+    ],
+    contentScript: `self.on('click', function (node, data) {
+      self.postMessage('https://vimeo.com' + node.href);
+    });`,
+    onMessage: (url)=> {
```
Comment (6a68) [inline lib/context-menu-handlers.js]: The contentScript and `onMessage` callback here are duplicates of the one below. Is it possible to specify two contexts for a single cm.Item? If not, maybe assign to a variable to avoid duplication

File: lib/launch-video.js [hunk 2]
```diff
@@ -13,7 +13,7 @@ function launchVideo(opts, panel) {
   let id;
 
   // TODO: submit a fix to getVideoId for this. #226
-  if (opts.url.indexOf('attribution_link')) {
+  if (opts.url.indexOf('attribution_link') > -1) {
```
Comment (6a68) [inline lib/launch-video.js]: I see some unrelated extra stuff in this PR. Are you just doing some unrelated cleanup work, or were these youtube-related changes unintentionally added to the commit?

Comment (meandavejustice) [inline lib/launch-video.js]: This was just a little cleanup I had forgotten to mention in the commit message

File: lib/context-menu-handlers.js (hunk 1 above)
Comment (meandavejustice) [inline lib/context-menu-handlers.js]: I haven't figured out a way to specify two contexts for a single item. Though that would be really nice. I tried to do that in a previous issue a couple of weeks ago.

I can pull the `contentScript` out into a variable.

File: lib/launch-video.js (hunk 2 above)
Comment (6a68) [inline lib/launch-video.js]: :+1:

File: lib/context-menu-handlers.js [hunk 3]
```diff
@@ -105,15 +105,32 @@ function init(panel) {
...
     label: contextMenuLabel,
     context: [
       cm.URLContext(['*.vimeo.com']),
       cm.SelectorContext('.contextclip-header a')
     ],
-    contentScript: `self.on('click', function (node, data) {
-      self.postMessage('https://vimeo.com/' + node.href);
-    });`,
+    contentScript: contentScriptVimeoCase,
+    onMessage: (url)=> {
```
Comment (6a68) [inline lib/context-menu-handlers.js]: This function is a dupe of the `onMessage` function that starts at line 134, would be good to extract it too

**Comment by 6a68** [comment]
Looks good! Happy to merge once the dupe function is addressed
